# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  pipelines:
  - pipeline: buildpipeline # Name of the pipeline resource.
    source: BuildPipeline # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

pool:
  vmImage: ubuntu-latest


steps:
- bash: |
    pwd
    ls
    ls $(Build.ArtifactStagingDirectory)
- bash: echo "Chained pipelines is an interesting concept."
