parameters:
# - name: myString
#   type: string
#   default: a string
# - name: myMultiString
#   type: string
#   default: default
#   values:
#   - default
#   - ubuntu
# - name: myNumber
#   type: number
#   default: 2
#   values:
#   - 1
#   - 2
#   - 4
#   - 8
#   - 16
# - name: myBoolean
#   type: boolean
#   default: true
- name: environments
  type: object
  default:
    Group1:
    - AA
    - BB
    - CC
    Group2:
    - DD
    - EE
    - FF

trigger: none

# jobs: 
# - job: stepList
#   steps: ${{ parameters.mySteplist }}

stages:
  - stage: Group1
    jobs:
    ${{ each environment in parameters.environments.Group1 }}:
      - job: ${{environment}}
        steps:
          - script: echo ${{ environment }}
