parameters:
# - name: myString
#   type: string
#   default: a string
# - name: myMultiString
#   type: string
#   default: default
#   values:
#   - default
#   - ubuntu
# - name: myNumber
#   type: number
#   default: 2
#   values:
#   - 1
#   - 2
#   - 4
#   - 8
#   - 16
# - name: myBoolean
#   type: boolean
#   default: true
- name: servers
  type: object
  default:
    Group1:
    - AA
    - BB
    - CC
    Group2:
    - DD
    - EE
    - FF

trigger: none

# jobs: 
# - job: stepList
#   steps: ${{ parameters.mySteplist }}

# stages:
#   - stage: Group1
#     jobs:
#     ${{ each server in parameters.servers.Group1 }}:
#       - job: "${{server}}"
#         steps:
#           - script: echo ${{ server }}

jobs:
- job: Test
  strategy:
    maxParallel: 2
    matrix: 
      US_IE:
        Location: US
        Browser: IE
      US_Chrome:
        Location: US
        Browser: Chrome
      Europe_Chrome:
        Location: Europe
        Browser: Chrome
