trigger: none

resources:
  webhooks:
    - webhook: CleanUpPREnv          ### Webhook alias
      connection: CleanUpPREnvWebhookConnection    ### Incoming webhook service connection
      filters:
      - path: action              ### JSON path in the payload
        value: closed    ### Expected value in the path provided

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    ### JSON payload data is available in the form of ${{ parameters.<WebhookAlias>.<JSONPath>}}
    script: |
      Write-Host ${{ parameters.CleanUpPREnv.action}}
      Write-Host ${{ parameters.CleanUpPREnv.number}}
