parameters:
# - name: myString
#   type: string
#   default: a string
# - name: myMultiString
#   type: string
#   default: default
#   values:
#   - default
#   - ubuntu
# - name: myNumber
#   type: number
#   default: 2
#   values:
#   - 1
#   - 2
#   - 4
#   - 8
#   - 16
# - name: myBoolean
#   type: boolean
#   default: true
- name: environments
  type: object
  default:
    Group1:
    - AA
    - BB
    - CC
    Group2:
    - DD
    - EE
    - FF
# - name: myStep
#   type: step
#   default:
#     script: echo my step
# - name: mySteplist
#   type: stepList
#   default:
#     - script: echo step one
#     - script: echo step two

trigger: none

# jobs: 
# - job: stepList
#   steps: ${{ parameters.mySteplist }}

- ${{ each environment in parameters.environments.Group1 }}:
  - script: echo ${{ environment }} 
# - job: myStep
#   steps:
#     - ${{ parameters.myStep }}
