resources:
  webhooks:
    - webhook: BasicWebhook          ### Webhook alias
      connection: BasicWebhookConnection    ### Incoming webhook service connection
      # filters:
      #   - path: repositoryName      ### JSON path in the payload
      #     value: maven-releases     ### Expected value in the path provided
      #   - path: action
      #     value: CREATED

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    ### JSON payload data is available in the form of ${{ parameters.<WebhookAlias>.<JSONPath>}}
    script: |
      Write-Host ${{ parameters.CleanUpPREnv.before}}
      Write-Host ${{ parameters.CleanUpPREnv.payload.before}}
      Write-Host ${{ variables.CleanUpPREnv.before}}
