pr: none
trigger: none

resources:
  webhooks:
    - webhook: BasicWebhook          ### Webhook alias
      connection: BasicWebhookConnection    ### Incoming webhook service connection
      # filters:
      #   - path: repositoryName      ### JSON path in the payload
      #     value: maven-releases     ### Expected value in the path provided
      #   - path: action
      #     value: CREATED

steps:
- script: |
    echo ${{parameters.BasicWebhook.myProp}}

