
resources:
  webhooks:
    - webhook: CleanUpPREnv          ### Webhook alias
      connection: CleanUpPREnvWebhookConnection    ### Incoming webhook service connection
      filters:
        - path: action
          value: synchronize

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    ### JSON payload data is available in the form of ${{ parameters.<WebhookAlias>.<JSONPath>}}
    script: |
      Write-Host ${{ parameters.CleanUpPREnv.action}}
      Write-Host ${{ parameters.CleanUpPREnv.number}}
